# Generated by Django 2.2.1 on 2019-09-08 08:45

import app.core.storage_backends
import app.product.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cost', models.FloatField(default=0)),
                ('sale_of', models.FloatField(default=0)),
                ('title', models.TextField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, storage=app.core.storage_backends.MediaStorage(), upload_to=app.product.models.Product.product_images_path)),
                ('product_external_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
